version: '3.1'

services:
  db:
    image: mysql
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: test
    ports:
      - 3306:3306
    
  node:
    container_name: node
    build: .
    ports:
      - 8080:3000
    depends_on:
      - db