version: '3.1'

services:
  db:
    image: mysql:latest
    command: --innodb-use-native-aio=0
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=test
      - MYSQL_DATABASE=testdb
    networks:
      - node-network
    
  node:
    build: .
    volumes:
      - ${PWD}:/app
    depends_on:
      - db
    networks:
      - node-network
    command: sh -c './wait-for-it.sh -t 0 db:3306 -- node index.js'

  nginx:
    restart:
      always
    container_name: nginx
    depends_on:
      - node
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - 8080:80
    networks:
      - node-network


networks:
  node-network:
    driver: bridge